version: '3.7'
services:

    ghsec-jira:
      build: .
      volumes:
        - $PWD:/opt/ghsec-jira

    # For local development, use Composer via 'docker-compose run --rm composer
    # install'.
    composer:
      image: composer:2.1.6
      volumes:
        - $PWD:/app
